### ISSUE TITLE
Poor user experience with auto-logout feature

### ISSUE THREAD

**Issue by SunSparc** [hashicorp/dev-portal#1324]
I want to comment that I like the new design and the ability to login to the documentation so that I can bookmark pages, etc. However, I have noticed that if I am signed in, and then leave the page for a while, it will automatically log me out and redirect me to the home page. This is frustrating when I leave a couple of documentation pages open that I was researching only to come back and have those pages essentially wiped out. Sometimes I can click the back button and get back to the page I was on, sometimes I cannot. Either way, it provides a poor user experience.

**Comment by ashleemboyer** [comment]
Hello @SunSparc! Thanks so much for reporting this issue, and apologies for the frustration you were experiencing. We totally understand! ❤️ In the last two weeks since your report, we've made a couple of updates and you should no longer experience this problem. Please let us know if that's not the case, and thanks again! 😊
